apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: post-upgrade-testing
  name: kdump-job-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]
