apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kdump-job-rolebinding
  namespace: post-upgrade-testing
subjects:
- kind: ServiceAccount
  name: kdump-job-sa
  namespace: post-upgrade-testing
roleRef:
  kind: Role
  name: kdump-job-role
  apiGroup: rbac.authorization.k8s.io