FROM quay.med.one:8443/openshift/ubi8/ubi

# Copy the RPM packages to the container
COPY rpms/ /tmp/rpms/

# Install necessary packages and cleanup
RUN yum localinstall -y /tmp/rpms/*.rpm && \
    yum clean all && \
    rm -rf /var/cache/yum /tmp/rpms

# This ENTRYPOINT take care of the vmlinux kernel version path, 
# When we run this container image we only need to mount and pass the vmcore file 
# Example: podman run --rm -it -v /path/to/vmcore:/vmcore:Z kdump-crash-tool:<kernel-version-tag> /vmcore
ENTRYPOINT ["crash", "/usr/lib/debug/lib/modules/4.18.0-5.el8.x86_64/vmlinux"]