FROM quay.med.one:8443/openshift/ubi8/ubi

# Copy the RPM packages to the container
COPY rpms/ /tmp/rpms/

# Install necessary packages
RUN yum localinstall -y /tmp/rpms/*.rpm && \
    yum clean all && \
    rm -rf /var/cache/yum

# Set up the entry point to use the crash utility
ENTRYPOINT ["crash", "/usr/lib/debug/lib/modules/4.18.0-5.el8.x86_64/vmlinux"]