apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 50-worker-extensions
spec:
  config:
    ignition:
      version: 3.1.0
  extensions:
    - crash
